### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'header')

### ISSUE THREAD

**Issue by IrinaLuminesk** [SortableJS/vue.draggable.next#254]
I currently getting this error on vue 3. This is my code
![image](https://github.com/SortableJS/vue.draggable.next/assets/100247516/0df18eb8-8567-4fdc-844e-0ec808f35a7e)
![image](https://github.com/SortableJS/vue.draggable.next/assets/100247516/e2fdce58-52fa-42c9-a04e-aca36993363b)

And this is the error show on my browser
![image](https://github.com/SortableJS/vue.draggable.next/assets/100247516/c06c05df-b751-4fe6-8dc7-4bfab124933f)

**Comment by vladfr** [comment]
Getting this too. And if you add the `#header` slot, you bump into other errors. It's because `this.$scopedSlots` is undefined, but I have no idea why. This happens only in very recent versions of Vue3. It didn't use to be like this before.

I'm on `vue@3.4.19` and using Nuxt.

Interestingly enough, on Vue 3.4.15 with a default Vuetify setup, this library works with the same code.

**Comment by bblumenfelder** [comment]
Getting the same error, but I'm not willing to install Vuetify :)
Did you find another solution?

**Comment by zhelingwang** [comment]
package version:
`"vue": "^3.4.21", "vuedraggable": "^4.0.1"`

code:
```
<draggable :list="myArray" item-key="name" ghost-class="ghost" @start="drag = true" @end="drag = false">
        <template #item="{ element }">
            <div class="list-group-item">{{ element.name }}</div>
        </template>
</draggable>
```
换 `"vuedraggable": "^4.0.1"` 这个版本后我这边正常, 没有出现这个错误了

**Comment by prashantnirgun** [comment]
this still not work with  "vuedraggable": "^4.0.1",

**Comment by Lippiece** [comment]
Updating Vue to latest will probably fix this, as it fixed mine.

**Comment by ReljaMihajlovic** [comment]
I fixed it by shutting down dev server and then running npm run dev again. "vue": "^3.4.27", "vuedraggable": "^4.1.0"

**Comment by emirrozerr** [comment]
> I fixed it by shutting down dev server and then running npm run dev again. "vue": "^3.4.27", "vuedraggable": "^4.1.0"

Same here!

**Comment by ecolovecat** [comment]
Just shut down the server and then rerun. If still not work, install to the  "vuedraggable": "^4.1.0", then rerun the server again

**Comment by chenyajin** [comment]
package version:
"vue": "^3.4.21", "vuedraggable": "^4.1.0"

solution:
delete node_modules and clean npm

it works for me!

**Comment by PrimozGodec** [comment]
Restarting the development server worked for me too.
